version: "3.8"

services:
  support-bot-template:
    build: .
    container_name: support-bot-template
    environment: &environment
      - BOT_CREDENTIALS=$BOT_CREDENTIALS  # cts_host@secret_key@bot_id
      - POSTGRES_DSN=postgres://postgres:postgres@support-bot-template-postgres/support_bot_template_db
      - REDIS_DSN=redis://support-bot-template-redis/0
      - DEBUG=true
      - SMARTLOG_DEBUG_HUIDS=$SMARTLOG_DEBUG_HUIDS
    ports:
      - "8000:8000"  # Отредактируйте порт хоста (первый), если он уже занят
    restart: always
    depends_on: &depends_on
      - postgres
      - redis
    logging: &logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    ulimits: &ulimits
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  support-bot-template-worker:
    build: .
    container_name: support-bot-template-worker
    # '$$' prevents docker-compose from interpolating a value
    command: bash -c 'PYTHONPATH="$$PYTHONPATH:$$PWD" saq app.worker.worker.settings'
    environment: *environment
    restart: always
    depends_on: *depends_on
    logging: *logging
    ulimits: *ulimits

  postgres:
    image: postgres:15.3-alpine
    container_name: support-bot-template-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=support_bot_template_db
    restart: always
    volumes:
      - ./.storages/postgresdata:/var/lib/postgresql/data
    logging: *logging

  redis:
    image: redis:7.0-alpine
    container_name: support-bot-template-redis
    restart: always
    volumes:
      - ./.storages/redisdata:/data
    logging: *logging
